server:
  port: 8081

#mybatis相关配置
mybatis:
  #配置实体类的包
  type-aliases-package: cn.cduestc.springcloud.pojo
  #配置mybatis配置文件的路径
  config-location:  classpath:mybatis/mybatis-config.xml
  #配置mybatis的mapper文件的位置
  mapper-locations: classpath:mybatis/mapper/*.xml

#spring相关配置
spring:
  #给该模块取个名字
  application:
      name: springcloud-provider-dept
  datasource:
    #更换连接数据库的数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8

#eureka相关配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/     #配置注册中心地址
  instance:
    instance-id: springcloud-provider-hystrix-dept8081   #配置服务名称
    prefer-ip-address: true   #显示服务的真实ip地址

#配置eureka页面对服务监控的信息
info:
  app.name: springcloud-zhanghu
  company.name: cduestc


